[package]
name = "oura-script-sink"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
oura = "1.6.0"
serde_json = "1.0.85"
